FROM hseeberger/scala-sbt:15.0.2_1.4.7_2.13.4 AS build
COPY . /goldrush/
WORKDIR /goldrush
RUN sbt '; set assemblyJarName in assembly := "app.jar"\
    ; set assemblyOutputPath in assembly := new File("/app/app.jar")\
    ;  assembly'

FROM ghcr.io/graalvm/graalvm-ce:21.0.0 AS run
WORKDIR /goldrush
COPY --from=build /app/app.jar app.jar
RUN gu install native-image
RUN native-image -jar app.jar application \
  --initialize-at-run-time=io.netty \
  --trace-class-initialization=org.slf4j.impl.SimpleLogger \
  -H:+ReportExceptionStackTraces
ENTRYPOINT ["application"]
